jocs/urls.py
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from main.views import *
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.views.generic.simple import redirect_to


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$',mainpage),
    #url(r'^user/(\w+)/$', userpage),
    url(r'^login/$','django.contrib.auth.views.login'),

    #PLATFORMS
    url(r'^PC$',gamesByPlatform),
    url(r'^PlayStation 3$',gamesByPlatform),
    url(r'^Xbox 360$',gamesByPlatform),
    url(r'^Wii$',gamesByPlatform),
    url(r'^PSP$',gamesByPlatform),
    url(r'^Nintendo DS$',gamesByPlatform),
    url(r'^Mobile$',gamesByPlatform),
    
    #GAME INFO
    url(r'^PC/([\w\s]+)$',gameDetails),
    url(r'^PlayStation 3/([\w\s]+)$',gameDetails),
    url(r'^Xbox 360/([\w\s]+)$',gameDetails),
    url(r'^Wii/([\w\s]+)$',gameDetails),
    url(r'^PSP/([\w\s]+)$',gameDetails),
    url(r'^Nintendo DS/([\w\s]+)$',gameDetails),
    url(r'^Mobile/([\w\s]+)$',gameDetails),
    #url(r'^jocs/', include('jocs.foo.urls')),

    #GET GAME BY 
    url(r'^company/([\w\s]+)$',gameByCompany),
    url(r'^type/([\w\s]+)$',gameByType),

    #REVIEW MANAGEMENT
    url(r'^review/add/([\w\s]+)/([\w\s]+)$',AddReview),
    url(r'^review/edit/([\w\s]+)/([\w\s]+)/([\w\s]+)$',EditReview),
    url(r'^review/delete/([\w\s]+)/([\w\s]+)/([\w\s]+)$',DeleteReview),

    #GAME MANAGEMENT
    url(r'^addGame/$',addGame),
    url(r'^deleteGame/([\w\s]+)/([\w\s]+)$',deleteGame),
    
    #COMPANY MANAGEMENT 
    url(r'^addCompany/$',addCompany),
    
    #PLATFORM - GAME MANAGEMENT 
    url(r'^addGameToPlat/([\w\s]+)$',addGameToPlat),
    
    #GAME - TYPE ASSIGMENT
    url(r'^asgnTypeOfGame/([\w\s]+)/$',asgnTypeOfGame),

    #GAME - CANCEL
    url(r'^cancel/([\w\s]+)/$',cancelGame),
    url(r'^cancel/$',redirect_to,{'url':'/'}),
    
    
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^logout/$',Logout),
    url(r'^register$',register))

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from datetime import *

# Create your models here.

class Company(models.Model):
    setUp = models.DateField(default=date.today)
    name = models.CharField(max_length=100,unique=True,primary_key=True)
    #image = models.ImageField(upload_to='companies',blank=True)
    
    def __unicode__(self):
        return self.name

class Platform(models.Model):
    Types=(
        ('PlayStation 3','PlayStation 3'),('Xbox 360','Xbox 360'),
        ('PC','PC'),('Nintendo DS','Nintendo DS'),('Mobile','Mobile'),('PSP','PSP'),('Wii','Wii')
    )
    releaseDate = models.DateField(default=date.today)
    name = models.CharField(max_length=100,choices=Types,unique=True,primary_key=True)
    #image = models.ImageField(upload_to='platforms',blank=True)

    def __unicode__(self):
        return self.name

class Made(models.Model):
    company = models.ForeignKey(Company)
    platform = models.ForeignKey(Platform)
    def __unicode__(self):
        return str(self.company)+'_'+str(self.platform)

class Game(models.Model):
    releaseDate = models.DateField(default=date.today)
    name = models.CharField(max_length=100,unique=True,primary_key=True)
    publisher = models.ForeignKey(Company)
    def __unicode__(self):
        return self.name

class SupportedBy(models.Model):
    game=models.ForeignKey(Game)
    platform=models.ForeignKey(Platform)
    def __unicode__(self):
        return str(self.game)+'_'+str(self.platform)

class BelongsTo(models.Model):
    game = models.ForeignKey(Game)
    Types=(
        ('Action','Action'),('Adventure','Adventure'),('Simulation','Simulation'),
        ('Sports','Sports'),('Driving','Driving'),('Strategy','Strategy'),('MMO','MMO'),
        ('Role','Role')
        )
    Type = models.CharField(max_length=15,choices=Types)
    def __unicode__(self):
        return str(self.game)+' Type: '+str(self.Type)
    
class GameReview(models.Model):
    RATING_CHOICES=((1,'one'),(2,'two'),(3,'three'),(4,'four'),(5,'five'))
    rating = models.PositiveSmallIntegerField('Rating(stars)',blank=False,default=3,choices=RATING_CHOICES)
    user = models.ForeignKey(User)
    date = models.DateTimeField(default=datetime.now)
    Comment = models.TextField(max_length=255,blank=True)
    game = models.ForeignKey(Game)
    platform = models.ForeignKey(Platform)
    city = models.CharField(max_length=100,blank=True)
    def __unicode__(self):
        return str(self.game)+'_'+str(self.user)

main/forms.py
from django.forms import *
from main.models import *

class addReviewForm(ModelForm):
    def __init__(self,user,gm,pform,*args,**kwrds):
        super(addReviewForm,self).__init__(*args,**kwrds)
        self.fields['user'].empty_label= None
        self.fields['user'].queryset = User.objects.filter(username=user)
        
        self.fields['game'].empty_label= None
        self.fields['game'].queryset = Game.objects.filter(name=gm)
       
        self.fields['platform'].empty_label= None
        self.fields['platform'].queryset = Platform.objects.filter(name=pform)
        
    class Meta:
        model=GameReview
        exclude=('date',)
        
class editReviewForm(ModelForm):
    def __init__(self,user,gm,pform,*args,**kwrds):
        super(editReviewForm,self).__init__(*args,**kwrds)
                
        self.fields['user'].empty_label= None
        self.fields['user'].queryset = User.objects.filter(username=user)
        
        self.fields['game'].empty_label= None
        self.fields['game'].queryset = Game.objects.filter(name=gm)
        
        self.fields['platform'].empty_label= None
        self.fields['platform'].queryset = Platform.objects.filter(name=pform)
        
    class Meta:
        model=GameReview        
        exclude=('date')
        
class addGameForm(ModelForm):
    def __init__(self,*args,**kwrds):
        super(addGameForm,self).__init__(*args,**kwrds)
        self.fields['releaseDate'].help_text = "* (dd/mm/yyyy)"
    class Meta:
        model=Game
        
class addCompanyForm(ModelForm):
    def __init__(self,*args,**kwrds):
        super(addCompanyForm,self).__init__(*args,**kwrds)
        self.fields['setUp'].help_text = "* (dd/mm/yyyy)"
    class Meta:
        model=Company
        
class addGameToPlatForm(ModelForm):
    def __init__(self,gm,*args,**kwrds):
        super(addGameToPlatForm ,self).__init__(*args,**kwrds)
        self.fields['game'].empty_label = None
        self.fields['game'].queryset = Game.objects.all().filter(name=gm)
    class Meta:
        model=SupportedBy
        
class asgnGameTypeOfGameForm(ModelForm):
    def __init__(self,gm,*args,**kwrds):
        super(asgnGameTypeOfGameForm,self).__init__(*args,**kwrds)
        self.fields['game'].empty_label = None
        self.fields['game'].queryset = Game.objects.all().filter(name=gm)
        self.fields['Type'].empty_label = None
    class Meta:
        model=BelongsTo

main/views.py
# Create your views here.

from django.http import HttpResponse
from django.http import Http404
from django.http import HttpResponseRedirect
from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.shortcuts import render_to_response, get_object_or_404,redirect
from django.template import RequestContext
from django.template import Context
from django.template.loader import get_template
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required
from operator import itemgetter
from main.models import *
from datetime import *
from main import *
from forms import *
from django import forms

def mainpage(request):
    '''
    This function contains the main template as initial website
    '''
    template = get_template('main.html')
    variables = {
        'titleHead': 'GAMES DATABASE',
        'pagetitle': 'Welcome to the GamesDB',
        'user': request.user,
        }
    return render_to_response('main.html',variables)

@login_required(login_url='/login')
def gamesByPlatform(request):
    '''
    This function contains all the games bases on the platform
    '''
    template = get_template('info.html')
    tmp = request.path.split('/')[1]
    path = request.path
    try:
        coll = Made.objects.get(platform=tmp)
        collection = SupportedBy.objects.all().filter(platform=tmp)
            
        variables =Context({
            'Title':'List of '+tmp+' Games',
            'TYPE':tmp,
            'Date': coll.platform.releaseDate,
            'Made':coll.company.name,
            'set':coll.company.setUp,
            'result': collection,
            'user': request.user,
            'path': path,
        })
    except:
        variables =Context({
            'Title':'List of '+tmp+' Games',
            'user': request.user,
            'TYPE':tmp,
            'Message':'Games not added yet! ',
            'path':path,
        })
        return render_to_response('http404.html',variables)
    return render_to_response('info.html',variables)

@login_required(login_url='/login')
def gameDetails(request,ref):
    '''
    This function show the details of the Game selectes and the platform which
    the belongs to
    '''
    template = get_template('details.html')
    gameInfo = SupportedBy.objects.all().filter(game=ref)
    Types = BelongsTo.objects.filter(game=ref)
    Publisher = Game.objects.get(name=ref)
    Gname = request.path.split('/')[2]
    Reviews = GameReview.objects.all().filter(game=Gname)
    dic=[]
    dic2=({})
    cid=0
    comments = {}
    average = 0
    #try:
    for rv in Reviews:
        cid=cid+1
        dic2=({
                'id': cid,
                'Rid':rv.id,
                'user': str(rv.user),
                'Comment':rv.Comment,
                'rate':rv.rating,
                'date':rv.date,
                'city':str(rv.city),
                })
        average = average + rv.rating
        dic.append(dic2)
    if average>0:
        average = float(average)
        average=average/cid
    print average
    dic = sorted(dic, key=lambda k: k['date'])
    for item in gameInfo:
        elem = [item.game.name]
    types = [str(t.Type) for t in Types]
    plat = [str(p.platform.name) for p in gameInfo]

    variables = Context({
        'titleHead': 'GamesDB',
        'pageTitle': 'Characteristics of ',
        'name':elem[0],
        'date': Publisher.releaseDate,
        'type':types ,
        'average':average,
        'rvs':cid,
        'platform':plat,
        'company': Publisher.publisher.name,
        'user': request.user,
        'COMMENTS':'USERS REVIEWS',
        'reviews':dic,
        'RATING_CHOICES':GameReview.RATING_CHOICES,
        'path':request.path,
        })
    #except:
    #    variables = Context({
    #         'titleHead': 'GamesDB',
    #         'user': request.user,
    #         'Message':'This requested Game does not exist!',
    #    })
    #    return render_to_response('http404.html',variables)
    return render_to_response('details.html',variables)

@login_required(login_url='/login')
def gameByType(request,ref):
    '''
    This function shows all the games by type
    '''
    try:
        Types = BelongsTo.objects.filter(Type=ref)
        g=[]
        tmp = ref
        for t in Types:
            g.append(str(t.game.name))
        variables=Context({
            'Title': 'All '+ref+' games',
            'result': g,
            'user': request.user,
            'TYPE':tmp,
    
            })
    except:
        raise Http404   
    return render_to_response('details3.html',variables)

@login_required(login_url='/login')
def gameByCompany(request,ref):
    '''
    This function shows all the games by company
    '''
    try:    
        Company = Game.objects.filter(publisher=ref)
        g=[]
        for game in Company:
            g.append(str(game.name))
        variables=Context({
            'Title': 'All '+ref+' games',
            'result': g,
            'user': request.user,
    
            })
    except:
        raise Http404
    return render_to_response('details3.html',variables)

@login_required(login_url='/login')
def Logout(request):
    '''
    This function logout the use and redirects him
    '''
    logout(request)
    return redirect('/')

def register(request):
    '''
    '''
    if request.method=='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect('/')
    else:
        form= UserCreationForm()
    return render_to_response('registration/register.html',{'form':form,'path':request.path},context_instance=RequestContext(request))

@login_required(login_url='/login')
def AddReview(request,pform,ref):
    '''
    Add a review to a game
    '''
    user = request.user
    path = pform+'/'+ref
    path1 = pform+' - '+ref
    path2 = request.path
    if request.method =='POST':
        form = addReviewForm(user,ref,pform,request.POST)
        print form
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/'+path)
    else:
        form = addReviewForm(user,ref,pform)
    return render(request,'comment.html',{'form':form,'path':path,'path1':path1,'path2':path2,'action':'CREATE REVIEW','flag':3})

@login_required(login_url='/login')
def EditReview(request,pform,ref,cid):
    '''
    Function to edit a review
    '''
    user = request.user
    path = pform+'/'+ref
    path2 = request.path
    review = GameReview.objects.get(pk=cid)
    
    Rid = review.id
    Game = str(review.game)
    Rating = str(review.rating)
    Comment = review.Comment
    Platform = str(review.platform)
    
    if review.user != request.user:
        return HttpResponseForbidden()
    if request.method =='POST':
        form = editReviewForm(user,ref,pform,request.POST,instance = review)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/'+path)
    else:
        form = editReviewForm(user,ref,pform, instance = review)
    return render(request,'comment.html',{
                                    'form':form,
                                    'path':path,
                                    'path2':path2,
                                    'action':'EDIT',
                                    'rate':Rating,
                                    'review':Comment,
                                    'game':Game,
                                    'pform':Platform,
                                    'flag':1
                                    })
@login_required
def DeleteReview(request,pform,ref,id):
    '''
    Function to delete a review
    '''
    rv = GameReview.objects.get(pk=id)
    if rv.user != request.user:
        return HttpResponseForbidden()
    rv.delete()
    return HttpResponseRedirect('/'+pform+'/'+ref)

@login_required(login_url='/login')
def addGame(request):
    '''
    Add a game using a form
    '''
    user = request.user
    current = request.path
    if request.method =='POST':
        form = addGameForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/asgnTypeOfGame/'+form.cleaned_data['name'])
    else:
        form = addGameForm()
    return render(request,'comment.html',{'form':form,'path':"/addCompany/",'path2':current,'action':'CREATE GAME','flag':2,'tag':'Add publisher'})

def deleteGame(request,pform,gm):
    '''
    Delete a game requested using its platform and game
    '''
    sup = SupportedBy.objects.all().filter(game = gm,platform=pform)
    rev = GameReview.objects.all().filter(game = gm,platform=pform)
    
    sup.delete()
    rev.delete()
    
    if not (SupportedBy.objects.all().filter(game = gm)):
        bel = BelongsTo.objects.all().filter(game = gm)
        gm = Game.objects.get(name = gm)
        
        bel.delete()
        gm.delete()

    return HttpResponseRedirect('/'+pform)

def addCompany(request):
    '''
    Add company
    '''
    user = request.user
    current = request.path
    if request.method =='POST':
        form = addCompanyForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/addGame')
    else:
        form = addCompanyForm()
    return render(request,'comment.html',{'form':form,'path':"/addGame",'path2':current,'action':'CREATE GAME','flag':4,'tag':'Back'})

def addGameToPlat(request,game):
    '''
    Assign game to platform
    '''
    user = request.user,
    current = request.path
    if request.method =='POST':
        form = addGameToPlatForm(game,request.POST)
        if form.is_valid():
            try:

main/templates/comment.html
{% extends "main.html"%}
{%load staticfiles%}
{% block head%}
		<script	src="http://code.jquery.com/jquery-1.9.1.js"></script>
		<script	src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <title>GamesDB - {{path1}}</title>
{%endblock%}
{%block content%}
    <p></p>
    <h2>{{action}}</h2>  
    <div class="left_content">
        <form method="post">{% csrf_token%}
            {{form.as_p}}<p>
                <input style="float: left; margin-left: 220px" type="submit" method = "post" value="Submit" onclick="parent.location='{{path2}}'">
                <input style="float: left;"  type="button" value="Cancel" onclick="parent.location='/cancel/{{game}}'">
        </form>
                {%if flag == 2%}
                    <p> </p>
                    <p></p>
                    <input style="float: left; margin-left: 35px"  type="button" value="{{tag}}" onclick="parent.location='{{path}}'">
                    <script >
                
                        $(function() {
                        $.getJSON('{% static "json/games.json" %}', function(data){
                        $("#id_name").autocomplete({
                        source: data
                        });
                        });
                        });
                    </script>                        
                {%endif%}
                                
                {% if flag == 4%}
                    <p></p>
                    <p></p>
                      <input style="float: left; margin-left: 35px"  type="button" value="{{tag}}" onclick="parent.location='{{path}}'">                    
                {%endif%}
                                
                                
                {%if flag == 3%}
                                    <script>
                                        
                        $("#id_city").autocomplete({
                                        source: function( request, response ) {
                                        $.ajax({
                                        url: "http://ws.geonames.org/searchJSON",
                                        dataType: "jsonp",
                                        data: {
                                            featureClass: "P",
                                            maxRows: 10,
                                            name_startsWith: request.term
                                        },
                                        success: function( data ) {
                                            response( $.map( data.geonames, function( item ) {
                                                return {
                                                    label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryName,
                                                    value: item.name,
                                                    stateOrProvince: item.adminName1,
                                                    countryName: item.countryName
                                                }
                                            }));
                                        }
                                    });
                                },
                                minLength: 2,
                                select: function( event, ui ) {
                                    if (ui.item) {
                                        $("#id_stateOrProvince").val(ui.item.stateOrProvince);
                                        $("#id_country").val(ui.item.countryName);
                                        $("#id_zipCode").val("");
                                    }
                                }
                            });
                    
                    </script>                     
                {%endif%}
                </p>


    </div>
{%endblock %}

main/templates/details.html
{% extends "main.html" %}
    {% block head%}
        <title>GamesDB - {{name}}</title>
    {% endblock %}
    {% block content %}
        <span   vocab="http://schema.org/"    typeof="CreativeWork">  
          <h1> 
            {{pageTitle}} <span property="name">{{name}}</span> 
          </h1>
          <!-- GAME DATA--> 
          <p >DATE: &nbsp <span property="dateCreated">{{date}}</span></p>  
            <p >TYPE:&nbsp
                {%for t in type%}
                <span property="applicationSubCategory" content={{t}}></span>
                <a href=/type/{{t}}> {{t}}</a>&nbsp
                {%endfor%}
            </p>
            <p>PLATFORM:&nbsp
                {%for p in platform%} 
                    {{p}}&nbsp
                {%endfor%}
             <span property="device" content={{platform|join:","|cut:" "}}></span>
            </p><span property="creator" content={{company|cut:" "}}></span>
            <p>PUBLISHER:&nbsp <a href=/company/{{company|urlencode}}> {{company}}</span></a></p>
            
            <div span style="margin-left:0cm" property="aggregateRating" typeof="AggregateRating">
                RATING:
                [ <span property="ratingValue">{{average|stringformat:".1f"}}</span>
                / <span property="bestRating">{{RATING_CHOICES.4.0}}</span> ]    
                based on  <span property="reviewCount">{{rvs}}</span> users
            </div>

            <p></p>
            <hr style="width: 830px; float: left; margin-left: 32px"></hr>

            <!-- REVIEWS -->
            <p><h3>{{COMMENTS}}</h3></p>
            {% for x in reviews %}
            <p span rel="review" typeof="Review">#
                <span property="id">{{x.id}}</span>
                <span property="author"> {{x.user}}</span>  
                <span property="datePublisher">{{x.date}}</span>
                {% if user.username == x.user%}
                    <INPUT  style="float: right; margin-right: 40px" VALUE= "EDIT" type="button" onClick="parent.location='/review/edit{{path}}/{{x.Rid}}'"></input>
                    <INPUT style="float: right" VALUE= "DELETE" type="button" onClick="parent.location='/review/delete{{path}}/{{x.Rid}}'"></input>
                {% endif%}             
                <span rel="reviewRating" typeof="Rating">
                    <span property="worstRating" content="1"></span>
                    <span property="bestRating" content="5"></span>
                    <br>Rate: [ <span property="ratingValue">{{x.rate}}</span>/5 ]
                </span>
                    <br><span property="reviewBody">{{x.Comment}}</span>
                    <br>From : [<span property="homeLocation">{{x.city}}</span>]

                <hr style="width: 830px; float: left; margin-left: 32px"> </hr>

            {% endfor %}

            </p>
        <FORM>
            <INPUT VALUE= "ADD REVIEW" type="button" onClick="parent.location='/review/add{{path}}'">
        </FORM>
{% endblock content %}

main/templates/details3.html
{% extends "main.html" %}
{% block head%}
<title>GamesDB - All {{TYPE}} Games </title>
{% endblock%}
    {% block content %}
        <h2>{{Title}}</h2>
        {% for item in result %}
        <p>{{item}}</p>
                {% empty %}
        <li> No elements added yet.</li>
        {% endfor %}
        </div>
        </div>
    {% endblock %}

main/templates/game.html
{% extends "main.html"%}
j
{%block content%}
    <p></p>
    <h2>{{action}}</h2>  
    <div class="left_content">
        <form action="{{path2}}" method="post">
            <h3> INSTRUCTIONS</h3>
            <p>To add a game properly, first you have to add a company. if it doesn't exist..
            <p>Add company [Publisher] <input style="float: left;"  type="submit" value="ADD" onclick="parent.location='/{{path}}/addElem/addCompany'">
            <p>Add game <input style="float: left;"  type="submit" value="ADD" onclick="parent.location='/{{path}}/addElem/addGame'">
            <p>Add game to each supported platform <input style="float: left;"  type="submit" value="ADD" onclick="parent.location='/{{path}}/addElem/addGameToPlat'">
            <p><input style="float: left;"  type="submit" value="Finish" onclick="parent.location='/{{path}}'">
            <input style="float: left;"  type="submit" value="Cancel" onclick="parent.location='/{{path}}'">
        </form>
    </div>
{%endblock %}

main/templates/http404.html
{% extends 'main.html'%}
{% block head%}
<title> GamesDB - {{TYPE}}</title>
{% endblock%}
    {% block content %}
        <p></p>
        <h2>{{Title}}</h2>
        <p> {{Message}}</p>
    {% endblock%}

main/templates/info.html
{% extends "main.html" %}
{% block head%}
 <title>GamesDB - {{TYPE}} </title>
{% endblock%}
    {% block content %}
        </p>
        <h2>{{Title}}</h2>
        <hr style="width: 275px; float: left; margin-left: 32px"><p>
            <p>Release Date: {{Date}} </p>
            <p>Made by: {{Made}} (Set up at:{{set}})</p>
        <hr style="width: 275px; float: left; margin-left: 32px"><p>
        <p><input style="float: left; margin-left: 35px" type="submit" value="ADD GAME" onclick="parent.location='addGame'"></p>
        <p></p>
        <p></p>
        {% for item in result %}


            <p><a href=/{{TYPE|urlencode}}/{{item.game.name|urlencode}}>{{item.game.name}}</a>
            <input style="margin-left: 35px" type="submit" value="DELETE" onclick="parent.location='deleteGame/{{TYPE}}/{{item.game.name}}'">
            <p></p>
        {% endfor %}

    {% endblock %}

main/templates/main.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    {% load staticfiles %}
    {% block head%}{%endblock%}
    <title>{{titleHead}}</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}" />
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css"/>

</head>
<body>
    
    <div id="wrap">
        <div class="header">
            <div class="logo"></div> 
        <div id="menu">
            <ul> 
                <li class="selected"><a href="/">Home</a></li>
                <li class="divider"></li>
                <li class="selected"><a href="/PC">PC</a></li>
                <li class="divider"></li>
                <li class="selected"><a href="/Xbox 360">XBOX360</a></li>
                <li class="divider"></li>
                <li class="selected"><a href="/PlayStation 3">PS3</a></li>
                <li class="divider"></li>
                <li class="selected"><a href="/Wii">Wii</a></li>
                <li class="divider"></li>
                <li class="selected"><a href="/PSP">PSP</a></li>
                <li class="divider"></li>
                <li class="selected"><a href="/Nintendo DS">NDS</a></li>
                <li class="divider"></li>
                <li class="selected"><a href="/Mobile">MOBILE</a></li>
                <li class="divider"></li>
                <li class="selected"><a href="/admin">ADMIN</a></li>
                <li class="divider"></li>
                <li class="selected">{% if user.username %}
                                        <a href="/logout/">Logout</a>
                                        {% else %}
                                        <a href="/login">Log in</a>
                                        <a href="/register">Register</a>
                                        {% endif %}</li>
                <li ><a href="">Welcome {{ user }}</a></li>
            </ul>
        </div> 

    </div>
        <div class="center_content">
        <h2>{{pagetitle}}</h2>
                {% if user.is_authenticated %}
                    {% block content %}{% endblock %}
                {%else%}
                    {% block contents %}{% endblock %}
                {% endif %}

        <p></p>
        </div>    
         <div class="clear">
            <p></p>
         </div>
    </div>
</body>
</html>